import createError from "../utils/createError.js";
import Message from "../models/message.model.js";
import Conversation from "../models/conversation.model.js";

export const createMessage = async (req, res, next) => {
  const newMessage = new Message({
    conversationId: req.body.conversationId,
    userId: req.userId,
    desc: req.body.desc,
  });
  try {
    const savedMessage = await newMessage.save();
    const conversation = await Conversation.findOne({
      id: req.body.conversationId,
    });
    conversation.readBySeller = req.userId === conversation.sellerId;
    conversation.readByBuyer = req.userId === conversation.buyerId;
    conversation.lastMessage = req.body.desc;
    await conversation.save();

    res.status(201).send(savedMessage);
  } catch (err) {
    next(err);
  }
};

export const getMessages = async (req, res, next) => {
  try {
    const messages = await Message.find({ conversationId: req.params.id });
    res.status(200).send(messages);
  } catch (err) {
    next(err);
  }
};
